# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4140e9b33050f0a0cbf80fad42bf1ca9c36ef9853243307e2a25731334bf02189937dae0235c962f5146014e2940fe8fd8bd3a054858c1f0c7892d080bbaa6b1

test:
  secret_key_base: 763c9a0914c285edfd81f151e8ceb80a11e62d8b73bbb27028605462c5f9ac2dedafe5ae87a1dd72b609e7897c184c2f831ec28b67bfe59976219e2a67a283e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
